import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";

const rootHtml = await readFile(new URL("../index.html", import.meta.url), "utf8");
const legacyHtml = await readFile(new URL("../legacy/index.html", import.meta.url), "utf8");
const classicHtml = await readFile(new URL("../classic/index.html", import.meta.url), "utf8");
const app = await readFile(new URL("../src/App.tsx", import.meta.url), "utf8");
const pdfDialog = await readFile(new URL("../src/PdfExportDialog.tsx", import.meta.url), "utf8");
const database = await readFile(new URL("../src/whiteboard-db.ts", import.meta.url), "utf8");
const legacyReader = await readFile(new URL("../src/legacy-reader.ts", import.meta.url), "utf8");
const pdf = await readFile(new URL("../src/pdf-export.ts", import.meta.url), "utf8");
const vite = await readFile(new URL("../vite.config.ts", import.meta.url), "utf8");

assert.match(rootHtml, /Offline Whiteboard/);
assert.match(rootHtml, /name="source-commit" content="__SOURCE_SHA__"/);
assert.match(app, /<Excalidraw/);
assert.match(app, /loadFromBlob/);
assert.match(app, /Browser drawings…/);
assert.match(app, /Export PDF…/);
assert.match(app, /className="theme-toggle"/);
assert.match(app, /ToggleTheme onSelect=\{applyTheme\}/);
assert.doesNotMatch(app, /SimpleMindmap|OutlineView|NodeDetailsDialog|mindmap-operations|custom search/i);
assert.match(database, /offline-whiteboard-v1/);
assert.match(database, /DRAWINGS_STORE/);
assert.match(database, /REVISIONS_STORE/);
assert.match(database, /ASSETS_STORE/);
assert.match(database, /WORKSPACE_STORE/);
assert.match(database, /minimumPerDrawing = 25/);
assert.match(app, /30_000/);
assert.match(app, /navigator\.storage\.persist/);
assert.match(app, /navigator\.storage\.estimate/);
assert.match(pdf, /5 \* 96 \/ 25\.4/);
assert.match(pdf, /10 \* MM_TO_PT/);
assert.match(pdf, /for \(let row[\s\S]*for \(let column/);
assert.match(pdf, /await import\("pdf-lib"\)/);
assert.match(pdf, /import\("jspdf"\)/);
assert.match(pdf, /import\("svg2pdf\.js"\)/);
assert.match(pdf, /await pdf\.svg\(svg/);
assert.match(pdf, /getDimensions:[\s\S]*planPdfRaster\(width, height, options\.quality\)/);
assert.match(pdf, /pdfExportAppState/);
assert.match(pdf, /document\.body\.appendChild\(anchor\)/);
assert.match(pdf, /URL\.revokeObjectURL\(url\), 60_000/);
assert.match(pdfDialog, /useState<PdfQuality>\("high"\)/);
assert.match(pdfDialog, /value="standard"/);
assert.match(pdfDialog, /value="high"/);
assert.match(pdfDialog, /value="maximum"/);
assert.match(pdfDialog, /Dark background and rendering/);
assert.match(pdfDialog, /Vector text and shapes stay sharp/);
assert.match(pdfDialog, /\{ layout, quality, selectionOnly, background, dark \}/);
assert.match(legacyHtml, /legacy-main\.tsx/);
assert.match(classicHtml, /legacy\/index\.html/);
assert.match(legacyReader, /transaction\(\["documents", "assets"\], "readonly"\)/);
assert.doesNotMatch(legacyReader, /\.put\(|\.add\(|\.delete\(/);
assert.match(vite, /legacy: "legacy\/index\.html"/);
assert.match(vite, /classic: "classic\/index\.html"/);
assert.doesNotMatch(rootHtml + legacyHtml + app, /https?:\/\/[^"']+\.(?:js|css|woff2?)/i);
await access(new URL("../vendor/pdf-lib.LICENSE.md", import.meta.url));
console.log("Static offline, routing, storage and source-metadata checks passed.");
